[package]
name = "ipd"
version = "2.0.0"
description = "A command-line tool for converting IP addresses to different formats."
edition = "2021"

[dependencies]
clap = { version = "4.5.22", features = ["derive", "cargo"] }
